### ISSUE TITLE
NTSC and PAL PIFROM causing issues?

### ISSUE THREAD

**Issue by vgturtle127** [tj90241/cen64#34] opened 2016-02-02 03:32 UTC
I have heard from a few people that when they try the supposed NTSC or PAL PIFROM dumps they don't work, only producing a black screen that goes nowhere (with any ROM).

I have tried as well, but CEN64 barely runs on my system anyway...

I would link to the dumps, but I think that may be frowned upon. :-1: 

They are put together and called pifrom.zip. Here are the hashes of the files:

NTSC PIFROM (file name is pifntsc.raw):
CRC32: 68DC7BF8
MD5: F92D467ABAFA081CEAD170918FD32883
SHA-1: 3A23E4CCCCA2CAD62A83EEA8519C7184FE1F7BE2

PAL PIFROM (file name is pifpal.raw):
CRC32: 2AE77E68
MD5: 2B6EEC586FAA43F3462333B844834554
SHA-1: 46CAE59D31F9298B93F3380879454FCEF54EE6CC

The zip file has these hashes:
CRC32: D0C2D468
MD5: BACE7A31EADDECCB0345500291379720
SHA-1: 75209ED921D62F01FBE0C29B32280BF0BF476C1D

Both the two dumps listed here and the dump of the Japanese PIFROM are 4096 bytes.

Looking at the PAL PIFROM dump in a hex editor, it looks very similar to the Japanese PIFROM.

The NTSC PIFROM looks very different, though. Does anybody know anything about either of these two dumps, or anything else about what I am experiencing? Something seems off...

Anyway, any information or assistance would be much appreciated.

**Comment by tj90241** [comment] 2016-02-02 05:54
I assume you mean NTSC-J? I have a NTSC-U PIFROM and it works fine.

The hash is this:
4921d5f2165dee6e2496f4388c4c81da

Maybe it's time I released the PIFROM dumper and made the ROM publicly available. I know of a Windows user who runs PAL PIFROM regularly on Windows 10 without issue, so I'm not sure what the problem is. It sounds like user-error, though due to my lack of any GUI or feedback, I can't really pin that on the user...

**Comment by vgturtle127** [comment] 2016-02-02 07:47
@tj90241 Oh, I guess that ROM is an NTSC PIFROM, then. I assumed mine was Japanese for some reason.

Anyway, the Japanese and PAL ROM don't work. NTSC works fine.

I may have bad dumps or something, but I'm pretty sure these have worked before. :disappointed: 

You should release that dumper and source, though. That would make it way easier for people to legally get a PIFROM, and also with the source released people could improve upon it or fix bugs and what not. Do you know how to dump it otherwise? I assumed the dumps made before were the results of decapping or something...

**Comment by Mastergatto** [comment] 2016-02-02 17:45
I thought the NTSC-U PIFROM and the NTSC-J one were the same? Why did they assume that this file called "pifntsc.raw" was the NTSC PIFROM?

**Comment by vgturtle127** [comment] 2016-02-03 00:07
@Mastergatto As far as I know, the NTSC and PAL PIFROM are more similar then the Japanese PIFROM.

None of them are the same, though. I assumed the pifntsc.raw file was an NTSC PIFROM because it was different than the Japanese PIFROM and similar to the PAL PIFROM. My thoughts were that the Japanese system might be different for the language or something. I don't know, I am questioning everything I know now... :disappointed:

**Comment by Mastergatto** [comment] 2016-02-09 22:39
Well, take a look at this: https://github.com/mikeryan/n64dev/blob/master/src/boot/pif.S#L15

NTSC-U and NTSC-J PIF ROM are the same one. i can assure you that this PIF ROM (sha1: 9174eadc0f0ea2654c95fd941406ab46b9dc9bdd) can boot any US or Japanese N64 games you want to run on CEN64.

**Comment by vgturtle127** [comment] 2016-02-10 00:29
@Mastergatto Thanks for that, I will have to double and triple check my dumps I guess.

As for the PAL PIFROM, I will test that as well.

**Comment by tj90241** [comment] 2016-06-17 13:45
Checksums are in place on these files now, so closing the issue.

**Closed by tj90241** 2016-06-17 13:45 UTC

**Comment by vgturtle127** [comment] 2016-08-03 03:05
@tj90241 Thanks!
