### ISSUE TITLE
Linker crash: (TDM-GCC)

### ISSUE THREAD

**Issue by Fendoroid** [tj90241/cen64#17] opened 2015-10-30 14:46 UTC
During compilation, I get a no such file error for tlb.h
```
D:/Downloads/cen64-angrylion/vr4300/cp0.h:14:21: fatal error: tlb/tlb.h: No such file or directory
 #include "tlb/tlb.h"
                     ^
compilation terminated.
mingw32-make.exe[2]: *** [CMakeFiles/cen64.dir/ai/controller.c.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles/cen64.dir/all] Error 2
mingw32-make.exe: *** [all] Error 2
CMakeFiles\cen64.dir\build.make:87: recipe for target 'CMakeFiles/cen64.dir/ai/controller.c.obj' failed
mingw32-make.exe[2]: Leaving directory 'D:/Downloads/cen64-angrylion/mingw-build'
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/cen64.dir/all' failed
mingw32-make.exe[1]: Leaving directory 'D:/Downloads/cen64-angrylion/mingw-build'
D:/Downloads/cen64-angrylion/mingw-build/Makefile:82: recipe for target 'all' failed
```

That's because "tlb/tlb.h" is in directory arch/x86_64.

**Comment by tj90241** [comment] 2015-10-31 00:54
Hmm, this is an error I have not seen before.

Can you please paste the output of `make VERBOSE=1` or `mingw32-make VERBOSE=1`, whichever you are using...?

Thanks.

**Comment by Fendoroid** [comment] 2015-10-31 11:33
Here is the [link to the log with verbose output](https://gist.github.com/Fendoroid/e1743312f136f138b567).

Also the [makefile](https://gist.github.com/Fendoroid/ca41d7ef2ac2cd03e16f) generated by cmake.

Following there is the full path from source and deps gathering to building (AFAIR):
* Downloaded cen64-angrylion-rdp from cen64.com main page
* Downloaded and installed OpenAL and OpenAL SDK 1.1 from openal.org
* Made Makefile and CodeBlocks project file with CMake (configured manually OPENAL_INCLUDE_DIR; left VR4300 busy wait detection and debug mmio register access unchecked)
* ran the `mingw32-make` under CodeBlocks
* got error.

Notes:
* I was using mingw32, only after I've noticed that there was a secret bug in cen64 (32bit). At the moment, I don't know which minGW x64 implementation should I use, since I have not found an official one.
* This error occurs also with master branch and using CMake generated makefile (without CodeBlocks project file).

PS: I would like to subscribe to the forums, but i got stuck to the turing test... (I don't know how to ) could you please send me a PM with the solution? (I'm not a spambot, I swear :sweat_smile: ) I'm not a native english speaker and don't know how to spell out Nintendo64 omitting every other letter, especially in written form. Maybe you can also consider to change with a more human pleasant captcha.

**Comment by tj90241** [comment] 2015-10-31 23:31
Hm, very weird... my guess is that this statement is not evaluating to true:
https://github.com/tj90241/cen64/blob/master/CMakeLists.txt#L34

Can you please paste the output of:
`gcc.exe -dumpmachine` and `gcc.exe -v`

The answer to the question is 'itno4'. I had a captcha before, but I regularly got a ton of bots and to hand-pick the registered users .This one seems to have stopped the spambots!

**Comment by Fendoroid** [comment] 2015-11-01 12:29
```
PS D:\Downloads\cen64-angrylion\mingw-build> gcc -dumpmachine
mingw32
PS D:\Downloads\cen64-angrylion\mingw-build> gcc -v
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gcc.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/4.8.1/lto-wrapper.exe
Target: mingw32
Configured with: ../gcc-4.8.1/configure --prefix=/mingw --host=mingw32 --build=mingw32 --without-pic --enable-shared --enable-static --with-gnu-ld --enable-lto --enable-libssp --disable-multilib --enable-languages=c,c++,fortran,objc,obj-c++,ada --disable-sjlj-exceptions --with-dwarf2 --disable-win32-registry --enable-libstdcxx-debug --enable-version-specific-runtime-libs --with-gmp=/usr/src/pkg/gmp-5.1.2-1-mingw32-src/bld --with-mpc=/usr/src/pkg/mpc-1.0.1-1-mingw32-src/bld --with-mpfr= --with-system-zlib --with-gnu-as --enable-decimal-float=yes --enable-libgomp --enable-threads --with-libiconv-prefix=/mingw32 --with-libintl-prefix=/mingw --disable-bootstrap LDFLAGS=-s CFLAGS=-D_USE_32BIT_TIME_T
Thread model: win32
gcc version 4.8.1 (GCC)
```

I didn't noticed that my gcc version is so old...

**Comment by tj90241** [comment] 2015-11-01 19:56
heh, -dumpmachine is supposed to spit out the target triplet... mingw32 does not seem correct (it should be i686-mingw32 or x86_64-mingw32 at least!)... so I guess I'll call that one a bug?

What version of TDM did you use? I built it with TDM a few months back. IIRC it was a 5.x release.

**Comment by Fendoroid** [comment] 2015-11-01 20:07
```
PS D:\> gcc -dumpmachine
x86_64-w64-mingw32
PS D:\> gcc -v
Using built-in specs.
COLLECT_GCC=C:\TDM-GCC-64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/5.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-5.1.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 5.1.0 (tdm64-1)
```

This is the output with TDM. The older one was about the official minGW release (really weird).

**Comment by tj90241** [comment] 2015-11-01 20:32
Okay, at least we have `gcc -dumpmachine` sorted out, which is at least getting the build to the linker error.

The linker errors are generally compiler crashes that can be fixed by killing `-flto` (which has the unfortunate side-effect of producing a binary that is not nearly as optimized).

I'll look into this one further and get back to you.

**Comment by tj90241** [comment] 2016-01-28 05:54
@PeterLemon - can I close this? You use TDM-GCC 5.2 to build without issues, right?

**Comment by tj90241** [comment] 2016-01-29 02:55
He regularly builds it with this: http://tdm-gcc.tdragon.net/

Closing as can't reproduce.

**Closed by tj90241** 2016-01-29 02:55 UTC
